export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as Cart } from "./Cart";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
export { default as SeeCartDetails } from "./SeeCartDetails";
export { default as SeeProductDetails } from "./SeeProductDetails";
export { default as SingleProduct } from "./SingleProduct";
export { default as Navbar2 } from "./Navbar2";
export { default as TeenProducts } from "./TeenProducts";
export { default as ChildProducts } from "./ChildProducts";
export { default as AdultProducts } from "./AdultProducts";
export { default as AllBooks} from "./AllBooks";
export { default as Footer } from "./Footer";
export { default as NotFound } from "./NotFound";
